[package]
name = "hello"
version = "0.1.0"
edition = "2021"

[dependencies]
kaiten_api = { path = "./src/kaiten_api"}
tokio = { version = "1.32.0", features = ["full"] }
wasm = { path = "./src/wasm"}
